2024-11-18 15:59:48,623 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\DanilKuchinsky\PycharmProjects\tests_12_4\tests_12_4.py", line 19, in test_run
    begun = Runner(311)
            ^^^^^^^^^^^
  File "C:\Users\DanilKuchinsky\PycharmProjects\tests_12_4\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-18 15:59:48,624 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\DanilKuchinsky\PycharmProjects\tests_12_4\tests_12_4.py", line 9, in test_walk
    human = Runner('Человек', -3)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DanilKuchinsky\PycharmProjects\tests_12_4\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -3
